[workspace]

resolver = "2"

members = [
  "bobestyrer",
  "uhuh",
  "uhuh-ext",
  "uhuh-tasks",
  "infinitask",
  "uhuh-axum",
  "uhuh-quick",
  "uhuh-exp",
  "daserror",
  "uhuh-cli",
  "uhuh-config", "uhuh-app",
]
